import "../../styles/globals.css"
import { Roboto } from 'next/font/google'
import Header from "@/components/ui/Header";
import Footer from "@/components/ui/Footer";
const roboto = Roboto({ subsets: ['latin'], weight: ['300', '400', '500'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
		<Header />
		{children}
		<Footer />
		</body>
    </html>
  )
}
